language: python

# earliest and latest supported; last release of every year; 14.0 for txi2p.plugins
matrix:
  include:
    - python: 2.7
      env: TOX_ENV=py27-tw102
    - python: 2.7
      env: TOX_ENV=py27-tw111
    - python: 2.7
      env: TOX_ENV=py27-tw120
    - python: 2.7
      env: TOX_ENV=py27-tw123
    - python: 2.7
      env: TOX_ENV=py27-tw132
    - python: 2.7
      env: TOX_ENV=py27-tw140
    - python: 2.7
      env: TOX_ENV=py27-tw155
    - python: 2.7
      env: TOX_ENV=py27-tw166
    - python: 2.7
      env: TOX_ENV=py27-tw179
    - python: 2.7
      env: TOX_ENV=py27-tw189
    - python: 2.7
      env: TOX_ENV=py27-twcurrent

    - python: pypy
      env: TOX_ENV=pypy-tw102
    - python: pypy
      env: TOX_ENV=pypy-tw111
    - python: pypy
      env: TOX_ENV=pypy-tw120
    - python: pypy
      env: TOX_ENV=pypy-tw123
    - python: pypy
      env: TOX_ENV=pypy-tw132
    - python: pypy
      env: TOX_ENV=pypy-tw140
    - python: pypy
      env: TOX_ENV=pypy-tw155
    - python: pypy
      env: TOX_ENV=pypy-tw166
    - python: pypy
      env: TOX_ENV=pypy-tw179
    - python: pypy
      env: TOX_ENV=pypy-tw189
    - python: pypy
      env: TOX_ENV=pypy-twcurrent

    # Test against Twisted trunk to detect potential future breakage early.
    - python: 2.7
      env: TOX_ENV=py27-twtrunk
    - python: pypy
      env: TOX_ENV=pypy-twtrunk

  allow_failures:
    # Don't fail on trunk versions.
    - env: TOX_ENV=py27-twtrunk
    - env: TOX_ENV=pypy-twtrunk
    # pypy is a bit sporadic
    - python: pypy

install:
  - pip install tox

script:
  - tox -e $TOX_ENV
