language: python

# earliest and latest supported; last release of every year; 14.0 for txi2p.plugins
matrix:
  include:
    - python: 2.7
      env: TOX_ENV=py27-tw102
    - python: 2.7
      env: TOX_ENV=py27-tw111
    - python: 2.7
      env: TOX_ENV=py27-tw120
    - python: 2.7
      env: TOX_ENV=py27-tw123
    - python: 2.7
      env: TOX_ENV=py27-tw132
    - python: 2.7
      env: TOX_ENV=py27-tw140
    - python: 2.7
      env: TOX_ENV=py27-tw155
    - python: 2.7
      env: TOX_ENV=py27-tw166
    - python: 2.7
      env: TOX_ENV=py27-tw179
    - python: 2.7
      env: TOX_ENV=py27-tw189
    - python: 2.7
      env: TOX_ENV=py27-twcurrent

    - python: 3.5
      env: TOX_ENV=py35-tw154
    - python: 3.5
      env: TOX_ENV=py35-tw155
    - python: 3.5
      env: TOX_ENV=py35-tw166
    - python: 3.5
      env: TOX_ENV=py35-tw179
    - python: 3.5
      env: TOX_ENV=py35-tw189
    - python: 3.5
      env: TOX_ENV=py35-twcurrent

    - python: 3.6
      env: TOX_ENV=py36-tw154
    - python: 3.6
      env: TOX_ENV=py36-tw155
    - python: 3.6
      env: TOX_ENV=py36-tw166
    - python: 3.6
      env: TOX_ENV=py36-tw179
    - python: 3.6
      env: TOX_ENV=py36-tw189
    - python: 3.6
      env: TOX_ENV=py36-twcurrent

    - python: 3.7
      env: TOX_ENV=py37-tw154
    - python: 3.7
      env: TOX_ENV=py37-tw155
    - python: 3.7
      env: TOX_ENV=py37-tw166
    - python: 3.7
      env: TOX_ENV=py37-tw179
    - python: 3.7
      env: TOX_ENV=py37-tw189
    - python: 3.7
      env: TOX_ENV=py37-twcurrent

    - python: pypy
      env: TOX_ENV=pypy-tw102
    - python: pypy
      env: TOX_ENV=pypy-tw111
    - python: pypy
      env: TOX_ENV=pypy-tw120
    - python: pypy
      env: TOX_ENV=pypy-tw123
    - python: pypy
      env: TOX_ENV=pypy-tw132
    - python: pypy
      env: TOX_ENV=pypy-tw140
    - python: pypy
      env: TOX_ENV=pypy-tw155
    - python: pypy
      env: TOX_ENV=pypy-tw166
    - python: pypy
      env: TOX_ENV=pypy-tw179
    - python: pypy
      env: TOX_ENV=pypy-tw189
    - python: pypy
      env: TOX_ENV=pypy-twcurrent

    - python: pypy3.5
      env: TOX_ENV=pypy35-tw154
    - python: pypy3.5
      env: TOX_ENV=pypy35-tw155
    - python: pypy3.5
      env: TOX_ENV=pypy35-tw166
    - python: pypy3.5
      env: TOX_ENV=pypy35-tw179
    - python: pypy3.5
      env: TOX_ENV=pypy35-tw189
    - python: pypy3.5
      env: TOX_ENV=pypy35-twcurrent

    # Ubuntu Xenial packages Twisted 16.0.0
    - python: 2.7
      env: TOX_ENV=py27-tw160

    # Test against Twisted trunk to detect potential future breakage early.
    - python: 2.7
      env: TOX_ENV=py27-twtrunk
    - python: 3.5
      env: TOX_ENV=py35-twtrunk
    - python: 3.6
      env: TOX_ENV=py36-twtrunk
    - python: 3.7
      env: TOX_ENV=py37-twtrunk
    - python: pypy
      env: TOX_ENV=pypy-twtrunk
    - python: pypy3.5
      env: TOX_ENV=pypy-twtrunk

  allow_failures:
    # Don't fail on trunk versions.
    - env: TOX_ENV=py27-twtrunk
    - env: TOX_ENV=py35-twtrunk
    - env: TOX_ENV=py36-twtrunk
    - env: TOX_ENV=py37-twtrunk
    - env: TOX_ENV=pypy-twtrunk
    - env: TOX_ENV=pypy35-twtrunk
    # pypy is a bit sporadic
    - python: pypy
    - python: pypy3.5

install:
  - pip install tox

script:
  - tox -e $TOX_ENV
