version: 2.1

orbs:
  # Get easier access to the Windows machine executor.
  win: "circleci/windows@4.1.1"

jobs:
  tests:
    parameters:
      image-base:
        type: "string"
      python-version:
        type: "string"
      twisted-version:
        type: "string"

    docker:
      - image: "<< parameters.image-base >>:<< parameters.python-version >>"

    steps:
      - "checkout"
      - run:
          name: "Setup Test Environment"
          command: |
            python -m pip install tox

      - run:
          name: "Run Tests"
          command: |
            PY=$(echo "<< parameters.python-version >>" | sed -e s/\\.//)
            python -m tox -e py"${PY}"-tw<< parameters.twisted-version >>

workflows:
  version: 2

  tests:
    jobs:
      - "tests":
          matrix:
            parameters:
              image-base:
                - "cimg/python"

              python-version:
                - "3.7"
                - "3.8"
                - "3.9"
                - "3.10"

              twisted-version:
                - "trunk"
                - "current"
                - "222"
                - "192"

      - "tests":
          matrix:
            parameters:
              image-base:
                - "pypy"

              python-version:
                - "3.7"
                - "3.8"
                - "3.9"

              twisted-version:
                - "trunk"
                - "current"
                - "222"
                - "192"
